Repository Check-Data-Out/velog-dashboard-v2-fe, pull requests merged in 2025-02, with the labels that each got.

#10 [25.02.08 / TASK-109 / TASK-111] Feature - 샘플 로그인 및 글 바로가기 기능 추가
  .env.sample
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  eslint.config.mjs
  jest.config.ts
  package.json
  pnpm-lock.yaml
  setupTests.ts
  src/__mock__/handlers.ts
  src/__mock__/responses.ts
  src/__mock__/server.ts
  src/__test__/login.test.tsx
  src/__test__/main.test.tsx
  src/apis/instance.request.ts
  src/apis/user.request.ts
  src/app/(with-tracker)/(auth-required)/layout.tsx
  src/app/(with-tracker)/(auth-required)/leaderboards/Content.tsx
  src/app/(with-tracker)/(auth-required)/leaderboards/page.tsx
  src/app/(with-tracker)/(auth-required)/main/Content.tsx
  src/app/(with-tracker)/(auth-required)/main/page.tsx
  src/app/(with-tracker)/(login)/Content.tsx
  src/app/(with-tracker)/layout.tsx
  src/components/auth-required/header/Section.tsx
  src/components/auth-required/header/index.tsx
  src/components/auth-required/index.ts
  src/components/auth-required/leaderboards/Rank.tsx
  src/components/auth-required/leaderboards/Ranker.tsx
  src/components/auth-required/leaderboards/index.ts
  src/components/auth-required/main/Section/Graph.tsx
  src/components/auth-required/main/Section/index.tsx
  src/components/auth-required/main/Summary/BarContent.tsx
  src/components/auth-required/main/Summary/SidebarContent.tsx
  src/components/auth-required/main/Summary/index.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Icon/SvgrMock.tsx
  src/components/common/Icon/icons/Shortcut.svg
  src/components/common/Icon/icons/index.ts
  src/components/common/Icon/index.tsx
  src/components/common/QueryProvider.tsx
  src/constants/paths.constant.ts
  src/hooks/useResponsive.ts
  src/types/apis/index.ts
  src/types/dashboard.type.ts
  src/types/index.ts
  src/types/user.type.ts
  src/utils/index.tsx
  src/utils/queryUtil.ts
  src/utils/trackUtil.tsx
  tsconfig.json
Labels: documentation

#11 [25.02.09] Hotfix - 배포 전 전체 코드 정리, 핫픽스
  .env.sample
  readme.md
  src/app/(with-tracker)/(auth-required)/leaderboards/Content.tsx
  src/app/(with-tracker)/(auth-required)/main/Content.tsx
  src/app/(with-tracker)/(login)/Content.tsx
  src/components/auth-required/header/Section.tsx
  src/components/auth-required/header/index.tsx
  src/components/auth-required/main/Section/index.tsx
  src/components/auth-required/main/Summary/index.tsx
  src/utils/trackUtil.tsx
Labels: bug, enhancement

#13 [25.02.16 / TASK-118] Feature: 채널톡 추가 및 헤더 로고 클릭 동작 추가
  .env.sample
  package.json
  pnpm-lock.yaml
  src/apis/dashboard.request.ts
  src/apis/instance.request.ts
  src/apis/user.request.ts
  src/app/(with-tracker)/(auth-required)/layout.tsx
  src/app/(with-tracker)/(auth-required)/main/Content.tsx
  src/app/(with-tracker)/(auth-required)/main/page.tsx
  src/app/layout.tsx
  src/components/auth-required/header/Section.tsx
  src/components/auth-required/header/index.tsx
  src/components/auth-required/main/Section/Graph.tsx
  src/components/auth-required/main/Section/index.tsx
  src/components/auth-required/main/index.ts
  src/components/common/ChannelTalkProvider.tsx
  src/components/common/index.ts
  src/errors/fetch.error.ts
  src/errors/index.ts
  src/errors/main.error.ts
Labels: enhancement

#14 [25.02.25] Fix - useSearchParam > 제네릭 사용하여 타입 추론 정확히 하도록 수정
  .github/workflows/docker-publish.yaml
  src/app/(with-tracker)/(auth-required)/leaderboards/Content.tsx
  src/app/(with-tracker)/(auth-required)/main/Content.tsx
  src/components/auth-required/main/Section/index.tsx
  src/constants/index.ts
  src/constants/searchParams.constant.ts
  src/hooks/useSearchParam.ts
  src/types/index.ts
  src/types/searchParams.type.ts
Labels: bug, enhancement

#16 [25.02.26 / TASK-119] Feature - SEO 세팅
  .env.sample
  .github/workflows/docker-publish.yaml
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  public/opengraph-image.png
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/__mock__/handlers.ts
  src/apis/instance.request.ts
  src/app/(with-tracker)/(auth-required)/compare/page.tsx
  src/app/(with-tracker)/(auth-required)/leaderboards/page.tsx
  src/app/(with-tracker)/(auth-required)/main/page.tsx
  src/app/(with-tracker)/(login)/page.tsx
  src/app/layout.tsx
  src/app/robots.ts
  src/app/sitemap.ts
  src/components/auth-required/main/Section/index.tsx
  src/components/common/ChannelTalkProvider.tsx
  src/constants/env.constant.ts
  src/constants/index.ts
  src/utils/trackUtil.tsx
Labels: enhancement

#17 [25.02.27 / TASK-130] Feature - 빠른 조회 기능 구현 및 오류 수정
  src/app/layout.tsx
  src/components/auth-required/main/Section/Graph.tsx
  src/constants/env.constant.ts
Labels: bug, enhancement

#19 [25.02.28] 릴리즈 - Dev
  .env.sample
  .github/workflows/docker-publish.yaml
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  public/opengraph-image.png
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/__mock__/handlers.ts
  src/apis/instance.request.ts
  src/app/(with-tracker)/(auth-required)/compare/page.tsx
  src/app/(with-tracker)/(auth-required)/layout.tsx
  src/app/(with-tracker)/(auth-required)/leaderboards/page.tsx
  src/app/(with-tracker)/(auth-required)/main/page.tsx
  src/app/(with-tracker)/(login)/page.tsx
  src/app/layout.tsx
  src/app/robots.ts
  src/app/sitemap.ts
  src/components/auth-required/header/index.tsx
  src/components/auth-required/main/Section/Graph.tsx
  src/components/auth-required/main/Section/index.tsx
  src/components/common/ChannelTalkProvider.tsx
  src/constants/env.constant.ts
  src/constants/index.ts
  src/utils/trackUtil.tsx
Labels: enhancement
